1:
  api_id: ""
  api_hash: ""
  phone_number: ""
  session_name: "s1"
  from_group_link: ""
2:
  api_id: ""
  api_hash: ""
  phone_number: ""
  session_name: "s2"
  from_group_link: ""
3:
  api_id: ""
  api_hash: ""
  phone_number: ""
  session_name: "s3"
  from_group_link: ""
4:
  api_id: ""
  api_hash: ""
  phone_number: ""
  session_name: "s4"
  from_group_link: ""
